#use this program to make personalised story
gender = input("He or She").lower()
gender2 = input("His or Her").lower()
name = input("What is your name?").upper()
age = int(input("How old are you?"))
bowler = input("Who do you hate the most?").upper()
friend = input("Who is your best friend?").upper()
print("It was time, time to shine for the ledendary cricket player, " + name + ".")
print(+ gender + " is only " + str(age) + " but " + gender + " has already won the national cup.")
print(+ name + " was ready to strike " + gender2 + " however the opposing team changed bowlers.")
print("But they did not just pick any bowler they picked the intimadating " + bowler +".")
print("This was bad news for " + name + " as " + gender + " was rivals with " + bowler + ".")
print(+ name + " was supported by " + gender2 + " batting partner " + friend + ".")
print("The score anounced 6 runs from 1 ball, " + name + " knew " + gender + " had to hit it really far")
print(+ bowler + " ran fast hoping for a good spin, the ball bounced rapidly towards " + name + "." + gender)
print("hit it so high that it even went out of the stadium, that was a definite six and " + name + "'s team won the match.")